excerpt_separator: ""
highlighter: rouge
markdown: kramdown
url: http://bktid.github.io
title: Tim De Meyer
tagline: Coffee solves every problem! Either that, or a level of indirection...
description: What's in my drawer?
avatar: https://www.gravatar.com/avatar/5fe3e012c7ff4ad30e859e3016721ed9
paginate: 5