# Permalinks
# I have disabled all permalink config
# relative_permalinks: is unsupported by github pages
# also, permalink: breaks my links posted on twitter (removes .html extension) 
# permalink:           pretty
# relative_permalinks: true

# Setup
title:               Tim De Meyer
tagline:             'Coffee solves every problem! Either that, or a level of indirection...'
description:         'What is in my drawer?'
url:                 http://bktid.github.io
baseurl:             ''
paginate:            5

# Custom vars
version:             1.0.0

# bktid
highlighter: rouge
markdown: kramdown
avatar: https://www.gravatar.com/avatar/5fe3e012c7ff4ad30e859e3016721ed9
excerpt_separator: <!--more-->